# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/user/final-project/final-project-vivado/oled_demo/oled_demo.srcs/sources_1/bd/oled_demo/ip/oled_demo_axi_gpio_1_0/oled_demo_axi_gpio_1_0.xci
# IP: The module: 'oled_demo_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/user/final-project/final-project-vivado/oled_demo/oled_demo.gen/sources_1/bd/oled_demo/ip/oled_demo_axi_gpio_1_0/oled_demo_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'oled_demo_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/user/final-project/final-project-vivado/oled_demo/oled_demo.gen/sources_1/bd/oled_demo/ip/oled_demo_axi_gpio_1_0/oled_demo_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'oled_demo_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/user/final-project/final-project-vivado/oled_demo/oled_demo.gen/sources_1/bd/oled_demo/ip/oled_demo_axi_gpio_1_0/oled_demo_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'oled_demo_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/user/final-project/final-project-vivado/oled_demo/oled_demo.srcs/sources_1/bd/oled_demo/ip/oled_demo_axi_gpio_1_0/oled_demo_axi_gpio_1_0.xci
# IP: The module: 'oled_demo_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/user/final-project/final-project-vivado/oled_demo/oled_demo.gen/sources_1/bd/oled_demo/ip/oled_demo_axi_gpio_1_0/oled_demo_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'oled_demo_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/user/final-project/final-project-vivado/oled_demo/oled_demo.gen/sources_1/bd/oled_demo/ip/oled_demo_axi_gpio_1_0/oled_demo_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'oled_demo_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/user/final-project/final-project-vivado/oled_demo/oled_demo.gen/sources_1/bd/oled_demo/ip/oled_demo_axi_gpio_1_0/oled_demo_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'oled_demo_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
