# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/oled_demo/oled_demo.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==oled_demo || ORIG_REF_NAME==oled_demo} -quiet] -quiet

# IP: bd/oled_demo/ip/oled_demo_PmodOLED_0_0/oled_demo_PmodOLED_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==oled_demo_PmodOLED_0_0 || ORIG_REF_NAME==oled_demo_PmodOLED_0_0} -quiet] -quiet

# IP: bd/oled_demo/ip/oled_demo_processing_system7_0_0/oled_demo_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==oled_demo_processing_system7_0_0 || ORIG_REF_NAME==oled_demo_processing_system7_0_0} -quiet] -quiet

# IP: bd/oled_demo/ip/oled_demo_axi_gpio_0_0/oled_demo_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==oled_demo_axi_gpio_0_0 || ORIG_REF_NAME==oled_demo_axi_gpio_0_0} -quiet] -quiet

# IP: bd/oled_demo/ip/oled_demo_axi_gpio_1_0/oled_demo_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==oled_demo_axi_gpio_1_0 || ORIG_REF_NAME==oled_demo_axi_gpio_1_0} -quiet] -quiet

# IP: bd/oled_demo/ip/oled_demo_xbar_0/oled_demo_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==oled_demo_xbar_0 || ORIG_REF_NAME==oled_demo_xbar_0} -quiet] -quiet

# IP: bd/oled_demo/ip/oled_demo_ps7_0_axi_periph_0/oled_demo_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==oled_demo_ps7_0_axi_periph_0 || ORIG_REF_NAME==oled_demo_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/oled_demo/ip/oled_demo_rst_ps7_0_100M_0/oled_demo_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==oled_demo_rst_ps7_0_100M_0 || ORIG_REF_NAME==oled_demo_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/oled_demo/ip/oled_demo_auto_pc_0/oled_demo_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==oled_demo_auto_pc_0 || ORIG_REF_NAME==oled_demo_auto_pc_0} -quiet] -quiet

# XDC: /home/user/final-project/final-project-vivado/oled_demo/oled_demo.gen/sources_1/bd/oled_demo/oled_demo_ooc.xdc
